import { Cliente } from './cliente';

export const CLIENTES: Cliente[] = [
  {
    id: 1,
    nombre: 'Anibal',
    apellido: 'Mogollon',
    email: 'adjmogollon@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 2,
    nombre: 'Alicia',
    apellido: 'Castillo',
    email: 'alixicastillo59@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 3,
    nombre: 'Anibal',
    apellido: 'Mogollon R',
    email: 'anibalmogollon52@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 4,
    nombre: 'Miguel',
    apellido: 'Cervantes',
    email: 'miguelcervantes@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 5,
    nombre: 'Gabriel',
    apellido: 'Marquez',
    email: 'gabrielmarquez@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 6,
    nombre: 'Alexander',
    apellido: 'Dumas',
    email: 'alexanderdumas@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 7,
    nombre: 'Lyra',
    apellido: 'Belacqua',
    email: 'lyrabelacqua@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 8,
    nombre: 'Marisa',
    apellido: 'Coulter',
    email: 'marisacoulter@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 9,
    nombre: 'Iorek',
    apellido: 'Byrnison',
    email: 'IorekByrnison@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 10,
    nombre: 'Lord',
    apellido: 'Asriel',
    email: 'LordAsriel@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 11,
    nombre: 'Will',
    apellido: 'Parry',
    email: 'WillParry@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
  {
    id: 12,
    nombre: 'Serafina',
    apellido: 'Pekkala',
    email: 'SerafinaPekkala@gmail.com',
    createAt: '2020-12-17',
    foto: '',
  },
];
